%% runChapter51Experiment.m
% Chapter 5.1 Experiment v1.0
%
% This script generates the SECOND and THIRD panels needed for the Chapter
% 5.1 dataset/scenario illustration:
%
%   Panel 2: field boundary only
%            - only the real field outline is shown
%            - no prescription patches, no refill stations, no obstacles,
%              no crop rows, and no depot
%
%   Panel 3: synthetic prescription scenario
%            - real field boundary
%            - irregular localized spraying prescription patches
%            - irregular localized fertilization prescription patches
%            - candidate refill stations
%            - obstacle regions
%            - crop-row direction
%
% The FIRST panel, the original satellite image, is external and is NOT
% generated by this script.

clear; clc; close all;
addpath(genpath(fullfile(pwd, 'src')));

cfg = config();
rng(cfg.seed, 'twister');

fprintf('=== Chapter 5.1 Experiment v1.0 ===\n');
fprintf('Field file: %s\n', cfg.data.fieldFileName);

env = generateEnvironment(cfg);

timestamp = datestr(now, 'yyyymmdd_HHMMSS');
outDir = fullfile(cfg.paths.resultsDir, ['chapter5_1_', timestamp]);
if ~exist(outDir, 'dir')
    mkdir(outDir);
end

% Panel 2: boundary only.
figBoundary = figure('Name','Chapter 5.1 - Panel 2 - Boundary only','Color','w');
plotFieldBoundaryOnly(env, cfg);
set(findall(gcf, '-property', 'FontName'), 'FontName', 'Times New Roman');

drawnow;
saveFigureFiles(figBoundary, fullfile(outDir, 'panel2_field_boundary_only'), cfg.plot.saveDpi);

% Panel 3: synthetic prescription scenario.
figPrescription = figure('Name','Chapter 5.1 - Panel 3 - Synthetic prescription scenario','Color','w');
plotPrescriptionScenario(env, cfg);
set(findall(gcf, '-property', 'FontName'), 'FontName', 'Times New Roman');

drawnow;
saveFigureFiles(figPrescription, fullfile(outDir, 'panel3_synthetic_prescription_scenario'), cfg.plot.saveDpi);

save(fullfile(outDir, 'chapter5_1_environment.mat'), 'env', 'cfg');

fprintf('\nChapter 5.1 figures saved in:\n%s\n', outDir);
fprintf('Panel 2 boundary figure: %s\n', fullfile(outDir, 'panel2_field_boundary_only.png'));
fprintf('Panel 3 prescription scenario: %s\n', fullfile(outDir, 'panel3_synthetic_prescription_scenario.png'));
fprintf('Environment data: %s\n', fullfile(outDir, 'chapter5_1_environment.mat'));
