function newPos = thinkingInnovation(candidatePos, archive, iter, maxIter, cfg)
%THINKINGINNOVATION Thinking Innovation Strategy.
%
% v1.4 supports two modes:
%   1) 'original_adapted': closer to the uploaded TIS.m mechanism;
%   2) 'stage1_simple': the earlier stable simplified version.
%
% In the original TIS code, IE is taken from the memory person(1,:), IM is
% calculated from pi*IE*rand, and popnew is generated by a tangent nonlinear
% transformation plus a DOK-scaled current solution. Here the single-objective
% memory is replaced by a Pareto-archive information event.

if isempty(archive)
    newPos = candidatePos;
    return;
end

mode = 'original_adapted';
if isfield(cfg.alg, 'tisMode')
    mode = cfg.alg.tisMode;
end

ie = selectArchiveInformationEvent(archive);

switch lower(mode)
    case 'original_adapted'
        C = 0.5;
        progress = max(0, min(1, iter / maxIter));

        % Original TIS writes DOK2 = FES^10. For numerical stability in this
        % scheduling problem, the normalized progress is used.
        DOK1 = C + progress^C;
        DOK2 = progress^10;
        DOK = DOK1 + DOK2 + eps;

        IM = pi .* ie .* rand(size(candidatePos));
        popnew = tan(IM - 0.5) * pi + (candidatePos ./ DOK + ie);
        newPos = boundaryRecall(popnew, cfg.alg.lb .* ones(size(candidatePos)), cfg.alg.ub .* ones(size(candidatePos)));

    otherwise
        % Earlier stage-1 simplified TIS.
        DOK = 0.5 + 0.5 * (iter / maxIter)^2;
        randVec = rand(size(candidatePos));
        IM = ie + randVec .* (candidatePos - ie);
        perturb = tan(pi*(rand(size(candidatePos))-0.5)) * 0.05;
        newPos = DOK * candidatePos + (1-DOK) * IM + perturb;
        newPos = clampPosition(newPos, cfg.alg.lb, cfg.alg.ub);
end
end

function ie = selectArchiveInformationEvent(archive)
% Prefer sparse Pareto archive regions if crowding distance is available.

crowd = [archive.crowding];

if isempty(crowd) || all(~isfinite(crowd)) || all(crowd == 0)
    ie = archive(randi(numel(archive))).position;
    return;
end

finiteCrowd = crowd(isfinite(crowd));
if isempty(finiteCrowd)
    ie = archive(randi(numel(archive))).position;
    return;
end

crowd(~isfinite(crowd)) = max(finiteCrowd) + 1;
crowd = max(crowd, 0);
if sum(crowd) <= 0
    ie = archive(randi(numel(archive))).position;
    return;
end

prob = crowd(:) / sum(crowd);
edges = cumsum(prob);
idx = find(rand() <= edges, 1, 'first');
ie = archive(idx).position;
end
