function zone = createIrregularZone(center, baseRadius, fieldPoly, opts)
%CREATEIRREGULARZONE Create an irregular prescription/obstacle patch.
% The patch is generated by radial perturbation around a center point and
% then clipped by the field polygon.
%
% opts.numVertices        number of polygon vertices (e.g., 24-40)
% opts.perturbation       radial perturbation strength in [0, 1)
% opts.aspectRatioRange   [min max] vertical scaling range
% opts.rotationDeg        optional fixed rotation (deg); if omitted random

if nargin < 4 || isempty(opts)
    opts = struct();
end
if ~isfield(opts, 'numVertices'),      opts.numVertices = 28; end
if ~isfield(opts, 'perturbation'),     opts.perturbation = 0.28; end
if ~isfield(opts, 'aspectRatioRange'), opts.aspectRatioRange = [0.75, 1.25]; end
if ~isfield(opts, 'rotationDeg'),      opts.rotationDeg = 360*rand(); end

n = max(12, round(opts.numVertices));
theta = linspace(0, 2*pi, n+1);
theta(end) = [];

% Smooth random radial modulation.
raw = rand(1, n) - 0.5;
kernel = [1, 2, 3, 2, 1];
kernel = kernel / sum(kernel);
pad = [raw(end-2:end), raw, raw(1:3)];
smoothed = conv(pad, kernel, 'same');
smoothed = smoothed(4:end-3);
smoothed = smoothed - mean(smoothed);
if max(abs(smoothed)) > 0
    smoothed = smoothed / max(abs(smoothed));
end

amp = min(max(opts.perturbation, 0.05), 0.45);
radii = baseRadius * (1 + amp * smoothed);
radii = max(0.55 * baseRadius, radii);

aspect = opts.aspectRatioRange(1) + rand() * diff(opts.aspectRatioRange);
phi = deg2rad(opts.rotationDeg);

x0 = radii .* cos(theta);
y0 = aspect * radii .* sin(theta);
R = [cos(phi), -sin(phi); sin(phi), cos(phi)];
xy = R * [x0; y0];

x = center(1) + xy(1,:);
y = center(2) + xy(2,:);
rawPatch = polyshape(x, y, 'Simplify', true);
zone = intersect(rawPatch, fieldPoly);
zone = rmholes(zone);

if area(zone) <= 1e-6
    zone = createCircularZone(center, baseRadius, fieldPoly);
end
end
