function cfg = ensureChapter53Config(cfg)
%ENSURECHAPTER53CONFIG Fill missing fields for robust Chapter 5.3 execution.

if ~isfield(cfg, 'paths'), cfg.paths = struct(); end
if ~isfield(cfg.paths, 'projectRoot'), cfg.paths.projectRoot = pwd; end
if ~isfield(cfg.paths, 'dataDir'), cfg.paths.dataDir = fullfile(cfg.paths.projectRoot, 'data'); end
if ~isfield(cfg.paths, 'wktDir'), cfg.paths.wktDir = fullfile(cfg.paths.dataDir, 'wkt'); end
if ~isfield(cfg.paths, 'wktZip'), cfg.paths.wktZip = fullfile(cfg.paths.dataDir, 'wkt.zip'); end
if ~isfield(cfg.paths, 'resultsDir'), cfg.paths.resultsDir = fullfile(cfg.paths.projectRoot, 'results'); end
if ~exist(cfg.paths.resultsDir, 'dir'), mkdir(cfg.paths.resultsDir); end

if ~isfield(cfg, 'data'), cfg.data = struct(); end
if ~isfield(cfg.data, 'fieldFileName'), cfg.data.fieldFileName = 'ee_field_9.wkt'; end
if ~isfield(cfg.data, 'autoPickIfMissing'), cfg.data.autoPickIfMissing = true; end

if ~isfield(cfg, 'env'), cfg.env = struct(); end
cfg.env = fillStructDefaults(cfg.env, struct( ...
    'nSprayTasks', 6, ...
    'nFertTasks', 6, ...
    'nRefillCandidates', 4, ...
    'nObstacles', 2, ...
    'obstacleRadiusRange', [4,10], ...
    'obstacleSafetyMargin', 3.0, ...
    'transferCheckResolution', 1.0, ...
    'taskZoneRadiusRange', [8,16], ...
    'useIrregularPatches', true, ...
    'patchNumVertices', 28, ...
    'patchPerturbationRange', [0.18,0.35], ...
    'patchAspectRatioRange', [0.70,1.35], ...
    'obstaclePatchPerturbationRange', [0.10,0.25], ...
    'sameTypeOverlapToleranceArea', 0.5, ...
    'minPrescriptionPatchArea', 8.0, ...
    'maxPatchGenerationAttempts', 500, ...
    'gridResolution', 3.0, ...
    'rowSpacing', 6.0, ...
    'rowAngleDeg', NaN, ...
    'refillPreferBoundary', false, ...
    'includeKnownFieldObstacles', false));

if ~isfield(cfg, 'uav'), cfg.uav = struct(); end
cfg.uav = fillStructDefaults(cfg.uav, struct( ...
    'speed', 5.0, ...
    'sprayWidth', 8.0, ...
    'overlapRate', 0.15, ...
    'energyPerMeter', 0.055, ...
    'energyPerArea', 0.002, ...
    'maxEnergy', 450, ...
    'maxSegmentDistance', 750, ...
    'flightHeight', 3.0, ...
    'driftBase', 1.0, ...
    'driftHeightCoeff', 0.15, ...
    'driftSpeedCoeff', 0.08, ...
    'candidateAnglesDeg', 0:30:150));

if ~isfield(cfg, 'ugv'), cfg.ugv = struct(); end
cfg.ugv = fillStructDefaults(cfg.ugv, struct( ...
    'speed', 1.2, ...
    'fertWidth', 4.0, ...
    'energyPerMeter', 0.018, ...
    'maxEnergy', 700, ...
    'maxSegmentDistance', 1200, ...
    'minTurningRadius', 3.5, ...
    'rowDeviationWeight', 1.0));

if ~isfield(cfg, 'planner'), cfg.planner = struct(); end
cfg.planner = fillStructDefaults(cfg.planner, struct( ...
    'transferMode', 'visibility_fast', ...
    'lineCheckResolution', 1.0, ...
    'gridResolution', 5.0, ...
    'maxGridNodesWarning', 160000));

if ~isfield(cfg, 'conflict'), cfg.conflict = struct(); end
cfg.conflict = fillStructDefaults(cfg.conflict, struct( ...
    'safetyDistance', 8.0, ...
    'dt', 1.0, ...
    'waitPerConflict', 3.0, ...
    'enableRepair', true, ...
    'ignoreInitialTime', 8.0, ...
    'ignoreDepotRadius', 10.0));

if ~isfield(cfg, 'obj'), cfg.obj = struct(); end
cfg.obj = fillStructDefaults(cfg.obj, struct( ...
    'uavEnergyWeight', 1.0, ...
    'ugvEnergyWeight', 0.6, ...
    'coveragePenaltyWeight', 1000, ...
    'conflictPenaltyWeight', 100));

if ~isfield(cfg, 'alg'), cfg.alg = struct(); end
cfg.alg = fillStructDefaults(cfg.alg, struct( ...
    'popSize', 20, ...
    'maxIter', 20, ...
    'archiveSize', 50, ...
    'lb', -5, ...
    'ub', 5, ...
    'tisProbability', 0.65, ...
    'useOriginalAOOUpdate', true, ...
    'enableTIS', true, ...
    'tisMode', 'original_adapted', ...
    'aooStepInitial', 1.2, ...
    'aooStepFinal', 0.15, ...
    'sigmoidThreshold', 0.50, ...
    'minActiveRefill', 1));

if ~isfield(cfg, 'chapter53'), cfg.chapter53 = struct(); end
cfg.chapter53 = fillStructDefaults(cfg.chapter53, struct( ...
    'numFields', 30, ...
    'seeds', [2026,2027,2028], ...
    'popSize', 20, ...
    'maxIter', 20, ...
    'archiveSize', 50, ...
    'outputPrefix', 'chapter5_3_batch_validation', ...
    'fieldFiles', {{}}, ...
    'countryList', {{'ee','lt','nl'}}, ...
    'minArea_m2', 2500, ...
    'maxArea_m2', 300000, ...
    'maxShapeIndex', 4.5, ...
    'minCompactness', 0.03, ...
    'smallAreaThreshold_m2', 20000, ...
    'largeAreaThreshold_m2', 80000, ...
    'savePerRunMat', false, ...
    'saveWorkspace', true, ...
    'saveAllPlotData', true, ...
    'quickTest', false));
end

function s = fillStructDefaults(s, d)
names = fieldnames(d);
for i = 1:numel(names)
    name = names{i};
    if ~isfield(s, name) || isempty(s.(name))
        s.(name) = d.(name);
    end
end
end
